### ISSUE TITLE
그래프 생성시 오류

### ISSUE THREAD

**Issue by jhchoi09km** [jhchoi09/test-git-2#1]
[현상]
그래프 생성시 에러 메시지
[재현방법]
1. ssh 접속시 -Y 옵션 없이 접속
2. 서버 실행
3. 서버 접속
4. 값 입력 후 submit
5. 그래프 이미지가 출력되지 않음
[개선방향]
Matplotlib 관련 설정 변경

**Comment by jhchoi09km** [comment]
로그 확인결과 에러발생 코드

https://github.com/jhchoi09/test-git-2/blob/90f4335395d6aff9c70e0851e63aa9e792478dd6/graph.py#L26

**Comment by jhchoi09** [comment]
Fixed

**Comment by jhchoi09km** [comment]
Fixed
